name: Ultroid on GitHub Runner
on:
  workflow_dispatch:

jobs:
  run-ultroid:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Ultroid
        run: |
          git clone https://github.com/TeamUltroid/Ultroid.git
          cd Ultroid
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install -r requirements.txt
          echo "Starting Ultroid..."
          python3 -m pyUltroid
